import {
  BrainIcon,
  CalendarCheckIcon,
  ClipboardListIcon,
  DumbbellIcon,
  FileTextIcon,
  FlameIcon,
  SaladIcon,
  ScaleIcon,
  SearchIcon,
  SparklesIcon,
  TrendingUpIcon,
  UserIcon,
  UtensilsIcon,
  type LucideIcon,
} from "lucide-react";

/** 工具名 -> 中文展示名映射（含历史旧名，保证旧会话兼容） */
export const toolNameMap: Record<string, string> = {
  checkin_tool: "训练打卡",
  create_checkin_tool: "训练打卡",
  get_streak_tool: "连续打卡",
  query_checkins_tool: "打卡记录",
  query_stats_tool: "训练统计",
  list_plans_tool: "训练计划",
  query_plan_tool: "训练计划",
  create_plan_tool: "生成训练计划",
  create_diet_plan_tool: "生成饮食计划",
  adjust_plan_tool: "调整计划",
  update_plan_tool: "调整计划",
  get_user_profile_tool: "用户档案",
  update_user_profile_tool: "更新档案",
  query_body_tool: "身体数据",
  record_meal_tool: "记录饮食",
  query_diet_summary_tool: "饮食汇总",
  manage_meal_tool: "管理饮食",
  set_nutrition_goals_tool: "营养目标",
  get_exercises_tool: "动作库",
  search_knowledge_base: "知识库检索",
  read_kb_document: "知识库文档",
  recall_memory: "回忆记忆",
  save_preference: "记录偏好",
  save_user_fact: "记录信息",
  list_user_profile: "用户画像",
  save_event: "记录事件",
  skill_load_tool: "加载技能",
  get_user_summary_tool: "用户画像摘要",
  present_plan_tool: "计划提案",
  present_form_tool: "信息采集表单",
};

/** 工具名 -> 图标 */
export const toolIconMap: Record<string, LucideIcon> = {
  checkin_tool: CalendarCheckIcon,
  create_checkin_tool: CalendarCheckIcon,
  get_streak_tool: FlameIcon,
  query_checkins_tool: CalendarCheckIcon,
  query_stats_tool: TrendingUpIcon,
  list_plans_tool: ClipboardListIcon,
  query_plan_tool: ClipboardListIcon,
  create_plan_tool: ClipboardListIcon,
  create_diet_plan_tool: SaladIcon,
  adjust_plan_tool: ClipboardListIcon,
  update_plan_tool: ClipboardListIcon,
  get_user_profile_tool: UserIcon,
  update_user_profile_tool: UserIcon,
  query_body_tool: ScaleIcon,
  record_meal_tool: UtensilsIcon,
  query_diet_summary_tool: UtensilsIcon,
  manage_meal_tool: UtensilsIcon,
  set_nutrition_goals_tool: UtensilsIcon,
  get_exercises_tool: DumbbellIcon,
  search_knowledge_base: SearchIcon,
  read_kb_document: FileTextIcon,
  recall_memory: BrainIcon,
  save_preference: SparklesIcon,
  save_user_fact: SparklesIcon,
  list_user_profile: BrainIcon,
  save_event: SparklesIcon,
  skill_load_tool: SparklesIcon,
  get_user_summary_tool: UserIcon,
  present_plan_tool: ClipboardListIcon,
  present_form_tool: ClipboardListIcon,
};
