import {
  BrainIcon,
  CalendarCheckIcon,
  CalendarPlusIcon,
  CalendarX2Icon,
  ClipboardListIcon,
  DumbbellIcon,
  FileTextIcon,
  FlameIcon,
  PencilIcon,
  PlusIcon,
  SaladIcon,
  ScaleIcon,
  SearchIcon,
  Settings2Icon,
  SparklesIcon,
  Trash2Icon,
  TrendingUpIcon,
  UserIcon,
  UtensilsIcon,
  type LucideIcon,
} from "lucide-react";

/** 工具名 -> 中文展示名映射（含历史旧名，保证旧会话兼容） */
export const toolNameMap: Record<string, string> = {
  checkin_tool: "训练打卡",
  create_checkin_tool: "训练打卡",
  get_streak_tool: "连续打卡",
  query_checkins_tool: "打卡记录",
  query_stats_tool: "训练统计",
  list_plans_tool: "训练计划",
  query_plan_tool: "训练计划",
  create_plan_tool: "生成训练计划",
  create_diet_plan_tool: "生成饮食计划",
  get_plan_detail_tool: "查看计划",
  update_plan_tool: "更新计划",
  delete_plan_tool: "归档计划",
  add_plan_day_tool: "添加训练日",
  remove_plan_day_tool: "删除训练日",
  sync_plan_day_tool: "同步训练日",
  add_exercise_tool: "添加动作",
  update_exercise_tool: "修改动作",
  remove_exercise_tool: "删除动作",
  get_user_profile_tool: "用户档案",
  update_user_profile_tool: "更新档案",
  query_body_tool: "身体数据",
  record_meal_tool: "记录饮食",
  query_diet_summary_tool: "饮食汇总",
  manage_meal_tool: "管理饮食",
  set_nutrition_goals_tool: "营养目标",
  get_exercises_tool: "动作库",
  search_knowledge_base: "知识库检索",
  read_kb_document: "知识库文档",
  recall_memory: "回忆记忆",
  save_preference: "记录偏好",
  save_user_fact: "记录信息",
  list_user_profile: "用户画像",
  save_event: "记录事件",
  skill_load_tool: "加载技能",
  get_user_summary_tool: "用户画像摘要",
  present_plan_tool: "计划提案",
  present_form_tool: "信息采集表单",
  get_goal_knowledge_tool: "闯关知识",
  present_roadmap_tool: "路线图提案",
  create_roadmap_tool: "创建路线图",
  get_roadmap_tool: "闯关路线图",
  record_baseline_tool: "记录基线",
};

/** 工具名 -> 图标 */
export const toolIconMap: Record<string, LucideIcon> = {
  checkin_tool: CalendarCheckIcon,
  create_checkin_tool: CalendarCheckIcon,
  get_streak_tool: FlameIcon,
  query_checkins_tool: CalendarCheckIcon,
  query_stats_tool: TrendingUpIcon,
  list_plans_tool: ClipboardListIcon,
  query_plan_tool: ClipboardListIcon,
  create_plan_tool: ClipboardListIcon,
  create_diet_plan_tool: SaladIcon,
  get_plan_detail_tool: SearchIcon,
  update_plan_tool: Settings2Icon,
  delete_plan_tool: Trash2Icon,
  add_plan_day_tool: CalendarPlusIcon,
  remove_plan_day_tool: CalendarX2Icon,
  sync_plan_day_tool: CalendarPlusIcon,
  add_exercise_tool: PlusIcon,
  update_exercise_tool: PencilIcon,
  remove_exercise_tool: Trash2Icon,
  get_user_profile_tool: UserIcon,
  update_user_profile_tool: UserIcon,
  query_body_tool: ScaleIcon,
  record_meal_tool: UtensilsIcon,
  query_diet_summary_tool: UtensilsIcon,
  manage_meal_tool: UtensilsIcon,
  set_nutrition_goals_tool: UtensilsIcon,
  get_exercises_tool: DumbbellIcon,
  search_knowledge_base: SearchIcon,
  read_kb_document: FileTextIcon,
  recall_memory: BrainIcon,
  save_preference: SparklesIcon,
  save_user_fact: SparklesIcon,
  list_user_profile: BrainIcon,
  save_event: SparklesIcon,
  skill_load_tool: SparklesIcon,
  get_user_summary_tool: UserIcon,
  present_plan_tool: ClipboardListIcon,
  present_form_tool: ClipboardListIcon,
  get_goal_knowledge_tool: BrainIcon,
  present_roadmap_tool: ClipboardListIcon,
  create_roadmap_tool: ClipboardListIcon,
  get_roadmap_tool: ClipboardListIcon,
  record_baseline_tool: ScaleIcon,
};
