"""动作库种子数据"""
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.fitme.models.exercise import Exercise


SEED_EXERCISES = [
    {"name": "杠铃卧推", "name_en": "Barbell Bench Press", "muscle_group": "chest", "muscle_subgroup": "middle_chest", "category": "compound", "is_compound": True, "equipment": "barbell", "difficulty": "intermediate", "calories_per_min": 8.0, "description": "经典的胸部训练动作，主要锻炼胸大肌中部", "instructions": "1. 躺在平凳上，双手握杠铃，略宽于肩\n2. 将杠铃从架子上取下，缓慢下放至胸部\n3. 胸部发力将杠铃推回起始位置", "tips": "保持肩胛骨收紧，肘部与身体呈45度角"},
    {"name": "哑铃飞鸟", "name_en": "Dumbbell Fly", "muscle_group": "chest", "muscle_subgroup": "middle_chest", "category": "isolation", "is_compound": False, "equipment": "dumbbell", "difficulty": "beginner", "calories_per_min": 5.0, "description": "孤立训练胸大肌，增加胸肌宽度", "instructions": "1. 躺在平凳上，双手持哑铃伸直在胸部上方\n2. 缓慢向两侧打开手臂，感受胸肌拉伸\n3. 胸部发力将哑铃拉回起始位置", "tips": "手肘保持微弯，不要完全锁死"},
    {"name": "上斜哑铃卧推", "name_en": "Incline Dumbbell Press", "muscle_group": "chest", "muscle_subgroup": "upper_chest", "category": "compound", "is_compound": True, "equipment": "dumbbell", "difficulty": "intermediate", "calories_per_min": 7.0, "description": "重点锻炼上胸肌群", "instructions": "1. 将凳子调至30-45度角\n2. 双手持哑铃，掌心向前\n3. 推起哑铃至手臂伸直，缓慢下放", "tips": "凳子角度不宜超过45度，否则肩部参与过多"},
    {"name": "高位下拉", "name_en": "Lat Pulldown", "muscle_group": "back", "muscle_subgroup": "lats", "category": "compound", "is_compound": True, "equipment": "cable", "difficulty": "beginner", "calories_per_min": 6.0, "description": "训练背阔肌的经典动作", "instructions": "1. 坐在器械上，双手握横杆，略宽于肩\n2. 背部发力将横杆拉至锁骨位置\n3. 缓慢还原，感受背部伸展", "tips": "身体不要过度后仰，保持挺胸"},
    {"name": "杠铃划船", "name_en": "Barbell Row", "muscle_group": "back", "muscle_subgroup": "middle_back", "category": "compound", "is_compound": True, "equipment": "barbell", "difficulty": "intermediate", "calories_per_min": 7.0, "description": "增加背部厚度和力量的核心动作", "instructions": "1. 双脚与肩同宽，俯身至躯干与地面约45度\n2. 双手握杠铃，背部发力将杠铃拉向腹部\n3. 在顶点挤压背部肌肉，缓慢下放", "tips": "保持核心收紧，背部挺直，避免弓背"},
    {"name": "引体向上", "name_en": "Pull Up", "muscle_group": "back", "muscle_subgroup": "lats", "category": "compound", "is_compound": True, "equipment": "bodyweight", "difficulty": "advanced", "calories_per_min": 9.0, "description": "自重训练的王者动作，全面锻炼背部", "instructions": "1. 双手握横杆，略宽于肩，掌心向前\n2. 背部发力将身体拉起至下巴过杆\n3. 缓慢下放至手臂伸直", "tips": "避免摆动身体借力，初学者可用弹力带辅助"},
    {"name": "深蹲", "name_en": "Barbell Squat", "muscle_group": "legs", "muscle_subgroup": "quadriceps", "category": "compound", "is_compound": True, "equipment": "barbell", "difficulty": "intermediate", "calories_per_min": 10.0, "description": "下肢训练的王者动作，锻炼股四头肌、臀大肌", "instructions": "1. 将杠铃放在斜方肌上\n2. 双脚与肩同宽，下蹲至大腿与地面平行\n3. 脚跟发力站起", "tips": "保持膝盖与脚尖方向一致，核心收紧"},
    {"name": "腿举", "name_en": "Leg Press", "muscle_group": "legs", "muscle_subgroup": "quadriceps", "category": "compound", "is_compound": True, "equipment": "machine", "difficulty": "beginner", "calories_per_min": 7.0, "description": "安全的下肢训练动作，适合大重量训练", "instructions": "1. 坐在器械上，脚放在踏板上\n2. 蹬腿伸展但不要锁死膝盖\n3. 缓慢屈膝回到起始位置", "tips": "膝盖不要完全锁死，保持对肌肉的持续张力"},
    {"name": "箭步蹲", "name_en": "Walking Lunge", "muscle_group": "legs", "muscle_subgroup": "quadriceps", "category": "compound", "is_compound": True, "equipment": "bodyweight", "difficulty": "beginner", "calories_per_min": 8.0, "description": "功能性下肢训练，提升平衡和稳定性", "instructions": "1. 站直，双手叉腰或持哑铃\n2. 向前迈出一步，屈膝下蹲至后膝接近地面\n3. 前脚发力站起，换另一侧", "tips": "保持上身直立，前腿膝盖不超过脚尖"},
    {"name": "哑铃推举", "name_en": "Dumbbell Shoulder Press", "muscle_group": "shoulders", "muscle_subgroup": "front_delt", "category": "compound", "is_compound": True, "equipment": "dumbbell", "difficulty": "beginner", "calories_per_min": 6.0, "description": "锻炼三角肌前束和中束", "instructions": "1. 坐在凳子上，双手持哑铃与肩同高\n2. 向上推至手臂伸直\n3. 缓慢下放至起始位置", "tips": "避免使用过大重量导致借力，保持核心稳定"},
    {"name": "侧平举", "name_en": "Lateral Raise", "muscle_group": "shoulders", "muscle_subgroup": "side_delt", "category": "isolation", "is_compound": False, "equipment": "dumbbell", "difficulty": "beginner", "calories_per_min": 4.0, "description": "孤立训练三角肌中束，增加肩部宽度", "instructions": "1. 站直，双手持哑铃置于身体两侧\n2. 手臂微弯，向两侧抬起至与肩同高\n3. 缓慢下放", "tips": "不要借力甩动身体，控制动作节奏"},
    {"name": "杠铃弯举", "name_en": "Barbell Curl", "muscle_group": "arms", "muscle_subgroup": "biceps", "category": "isolation", "is_compound": False, "equipment": "barbell", "difficulty": "beginner", "calories_per_min": 4.0, "description": "经典的肱二头肌训练动作", "instructions": "1. 站直，双手握杠铃，掌心向上\n2. 屈肘将杠铃弯举至与肩同高\n3. 缓慢下放至起始位置", "tips": "避免身体前后晃动借力"},
    {"name": "三头下压", "name_en": "Tricep Pushdown", "muscle_group": "arms", "muscle_subgroup": "triceps", "category": "isolation", "is_compound": False, "equipment": "cable", "difficulty": "beginner", "calories_per_min": 4.0, "description": "训练肱三头肌的有效动作", "instructions": "1. 面对绳索器械，双手握绳\n2. 肘部贴近身体，向下压至手臂伸直\n3. 缓慢还原", "tips": "肘部保持固定位置，不要前后移动"},
    {"name": "平板支撑", "name_en": "Plank", "muscle_group": "core", "muscle_subgroup": "abdominals", "category": "isolation", "is_compound": False, "equipment": "bodyweight", "difficulty": "beginner", "calories_per_min": 3.0, "description": "核心稳定性训练的基础动作", "instructions": "1. 俯卧，手肘支撑在肩膀正下方\n2. 脚尖着地，身体呈一条直线\n3. 保持30-60秒", "tips": "收紧腹部和臀部，避免塌腰"},
    {"name": "卷腹", "name_en": "Crunches", "muscle_group": "core", "muscle_subgroup": "abdominals", "category": "isolation", "is_compound": False, "equipment": "bodyweight", "difficulty": "beginner", "calories_per_min": 4.0, "description": "针对腹直肌的经典训练", "instructions": "1. 仰卧，屈膝，双手放在头后或交叉在胸前\n2. 腹部发力卷起上背部\n3. 缓慢下放", "tips": "不要用手拉头部，注意力集中在腹部"},
    {"name": "哑铃肩后束弯举", "name_en": "Rear Delt Fly", "muscle_group": "shoulders", "muscle_subgroup": "rear_delt", "category": "isolation", "is_compound": False, "equipment": "dumbbell", "difficulty": "beginner", "calories_per_min": 4.0, "description": "训练三角肌后束", "instructions": "1. 俯身，双手持哑铃\n2. 手臂微弯，向两侧抬起挤压后肩\n3. 缓慢下放", "tips": "使用轻重量，感受后束肌肉发力"},
    {"name": "硬拉", "name_en": "Deadlift", "muscle_group": "back", "muscle_subgroup": "lower_back", "category": "compound", "is_compound": True, "equipment": "barbell", "difficulty": "advanced", "calories_per_min": 10.0, "description": "全身复合动作之王，锻炼后链肌群", "instructions": "1. 双脚与髋同宽，杠铃贴近小腿\n2. 臀部下沉，背部挺直，手握杠铃\n3. 腿部发力将杠铃拉起至身体直立\n4. 沿原路缓慢下放", "tips": "保持背部挺直，杠铃始终贴近身体"},
    {"name": "俯卧撑", "name_en": "Push Up", "muscle_group": "chest", "muscle_subgroup": "middle_chest", "category": "compound", "is_compound": True, "equipment": "bodyweight", "difficulty": "beginner", "calories_per_min": 6.0, "description": "经典自重胸部训练", "instructions": "1. 双手与肩同宽或略宽，身体呈直线\n2. 屈肘下放至胸部接近地面\n3. 胸部发力推起", "tips": "身体保持一条直线，收紧核心"},
    {"name": "山羊挺身", "name_en": "Back Extension", "muscle_group": "back", "muscle_subgroup": "lower_back", "category": "isolation", "is_compound": False, "equipment": "bodyweight", "difficulty": "beginner", "calories_per_min": 5.0, "description": "加强下背部力量，预防腰痛", "instructions": "1. 固定双脚，髋部靠在器械垫上\n2. 缓慢下放上半身\n3. 下背发力将上半身抬起", "tips": "不要过度后伸，感受下背部发力"},
    {"name": "保加利亚分腿蹲", "name_en": "Bulgarian Split Squat", "muscle_group": "legs", "muscle_subgroup": "quadriceps", "category": "compound", "is_compound": True, "equipment": "dumbbell", "difficulty": "intermediate", "calories_per_min": 9.0, "description": "单侧训练腿部力量和平衡性", "instructions": "1. 后脚放在凳子上，前脚向前跨步\n2. 屈前膝下蹲至后膝接近地面\n3. 前脚发力站起", "tips": "保持上身直立，前腿膝盖不超过脚尖"},
    {"name": "壶铃摆荡", "name_en": "Kettlebell Swing", "muscle_group": "full_body", "muscle_subgroup": None, "category": "compound", "is_compound": True, "equipment": "kettlebell", "difficulty": "intermediate", "calories_per_min": 12.0, "description": "高效燃脂的全身功能性训练", "instructions": "1. 双脚略宽于肩，双手握壶铃\n2. 髋部发力将壶铃向前上方摆荡至胸部高度\n3. 控制壶铃下落，重复动作", "tips": "发力来自髋部而非手臂，保持核心收紧"},
    {"name": "仰卧腿举", "name_en": "Lying Leg Curl", "muscle_group": "legs", "muscle_subgroup": "hamstrings", "category": "isolation", "is_compound": False, "equipment": "machine", "difficulty": "beginner", "calories_per_min": 5.0, "description": "孤立训练大腿后侧的腘绳肌", "instructions": "1. 俯卧在器械上，脚跟卡在滚垫下\n2. 屈膝将滚垫向臀部卷起\n3. 缓慢还原", "tips": "不要借力抬髋，保持骨盆贴紧器械"},
    {"name": "坐姿划船", "name_en": "Seated Cable Row", "muscle_group": "back", "muscle_subgroup": "middle_back", "category": "compound", "is_compound": True, "equipment": "cable", "difficulty": "beginner", "calories_per_min": 6.0, "description": "锻炼中背部肌群和菱形肌", "instructions": "1. 坐姿，双脚蹬踏板，双手握把手\n2. 背部发力将把手拉向腹部\n3. 在顶点挤压一秒钟，缓慢还原", "tips": "避免身体过度后仰，保持挺胸沉肩"},
    {"name": "哑铃耸肩", "name_en": "Dumbbell Shrug", "muscle_group": "back", "muscle_subgroup": "traps", "category": "isolation", "is_compound": False, "equipment": "dumbbell", "difficulty": "beginner", "calories_per_min": 4.0, "description": "训练斜方肌上部，增加肩部厚度", "instructions": "1. 站直，双手持哑铃置于身体两侧\n2. 向上耸肩至最高点，挤压斜方肌\n3. 缓慢下放", "tips": "不要转动颈部，保持头部中立位"},
    {"name": "双杠臂屈伸", "name_en": "Dips", "muscle_group": "chest", "muscle_subgroup": "lower_chest", "category": "compound", "is_compound": True, "equipment": "bodyweight", "difficulty": "advanced", "calories_per_min": 8.0, "description": "自重训练下胸和肱三头肌的黄金动作", "instructions": "1. 双手撑在双杠上，身体悬空\n2. 身体前倾30度，屈肘下放\n3. 胸部发力推起", "tips": "初学者可用弹力带辅助，肩关节有伤者慎做"},
    {"name": "坐姿哑铃弯举", "name_en": "Seated Dumbbell Curl", "muscle_group": "arms", "muscle_subgroup": "biceps", "category": "isolation", "is_compound": False, "equipment": "dumbbell", "difficulty": "beginner", "calories_per_min": 4.0, "description": "孤立训练肱二头肌，增加手臂围度", "instructions": "1. 坐在凳子上，手持哑铃\n2. 屈肘弯举至肩部\n3. 缓慢下放。可交替或同时进行", "tips": "保持肘部固定，不要前后摆动"},
    {"name": "站姿提踵", "name_en": "Standing Calf Raise", "muscle_group": "legs", "muscle_subgroup": "calves", "category": "isolation", "is_compound": False, "equipment": "barbell", "difficulty": "beginner", "calories_per_min": 5.0, "description": "训练小腿腓肠肌", "instructions": "1. 站直，脚尖踩在台阶边缘\n2. 脚尖发力将身体踮起到最高\n3. 缓慢下放至跟腱有拉伸感", "tips": "动作节奏要慢，顶峰收缩1-2秒"},
    {"name": "悬垂举腿", "name_en": "Hanging Leg Raise", "muscle_group": "core", "muscle_subgroup": "abdominals", "category": "isolation", "is_compound": False, "equipment": "bodyweight", "difficulty": "advanced", "calories_per_min": 7.0, "description": "高阶腹肌训练，同时锻炼握力", "instructions": "1. 双手悬挂在单杠上\n2. 腹部发力将腿抬起至与地面平行或更高\n3. 缓慢下放", "tips": "避免摆动借力，初学者可屈膝做"},
    {"name": "跑步机", "name_en": "Treadmill Running", "muscle_group": "full_body", "muscle_subgroup": None, "category": "cardio", "is_compound": False, "equipment": "machine", "difficulty": "beginner", "calories_per_min": 10.0, "description": "经典有氧运动，提升心肺功能", "instructions": "1. 设定速度和坡度\n2. 保持良好姿态，自然摆臂\n3. 持续20-45分钟", "tips": "保持身体直立，避免扶把手，选择合适的速度"},
    {"name": "划船机", "name_en": "Rowing Machine", "muscle_group": "full_body", "muscle_subgroup": None, "category": "cardio", "is_compound": False, "equipment": "machine", "difficulty": "beginner", "calories_per_min": 9.0, "description": "全身有氧运动，对关节友好", "instructions": "1. 坐在器械上，脚固定，手握把\n2. 腿部先发力，然后背部，最后手臂\n3. 恢复顺序相反", "tips": "发力顺序：腿→背→臂，恢复顺序：臂→背→腿"},
    {"name": "上斜杠铃卧推", "name_en": "Incline Barbell Press", "muscle_group": "chest", "muscle_subgroup": "upper_chest", "category": "compound", "is_compound": True, "equipment": "barbell", "difficulty": "intermediate", "calories_per_min": 7.0, "description": "杠铃版上胸训练，适合大重量", "instructions": "1. 凳子调至30-45度角\n2. 握杠铃略宽于肩\n3. 下放至锁骨附近，推起至手臂伸直", "tips": "触杠位置在上胸部而非胸部中部"},
    {"name": "面拉", "name_en": "Face Pull", "muscle_group": "shoulders", "muscle_subgroup": "rear_delt", "category": "isolation", "is_compound": False, "equipment": "cable", "difficulty": "beginner", "calories_per_min": 4.0, "description": "改善肩部健康的康复性训练", "instructions": "1. 将绳索调至面部高度\n2. 双手握绳，向面部拉至双手分开\n3. 挤压肩后束，缓慢还原", "tips": "手指分开与眉毛同高，外旋手腕"},
    {"name": "罗马椅侧屈", "name_en": "Side Bend on Roman Chair", "muscle_group": "core", "muscle_subgroup": "obliques", "category": "isolation", "is_compound": False, "equipment": "bodyweight", "difficulty": "beginner", "calories_per_min": 3.0, "description": "训练腹外斜肌", "instructions": "1. 侧卧在罗马椅上\n2. 侧腹发力将上半身向一侧抬起\n3. 缓慢下放，换边", "tips": "动作幅度不宜过大，控制节奏"},
    {"name": "杠铃臀推", "name_en": "Barbell Hip Thrust", "muscle_group": "legs", "muscle_subgroup": "glutes", "category": "compound", "is_compound": True, "equipment": "barbell", "difficulty": "intermediate", "calories_per_min": 8.0, "description": "锻炼臀大肌的最佳动作", "instructions": "1. 背部靠在凳子上，杠铃横放在髋部\n2. 臀部发力将杠铃向上推至身体呈水平\n3. 顶峰收缩后缓慢下放", "tips": "颈部自然放松，目光直视前方"},
    {"name": "哑铃卧推", "name_en": "Dumbbell Bench Press", "muscle_group": "chest", "muscle_subgroup": "middle_chest", "category": "compound", "is_compound": True, "equipment": "dumbbell", "difficulty": "intermediate", "calories_per_min": 7.0, "description": "哑铃版卧推，活动范围更大", "instructions": "1. 躺在平凳上，双手持哑铃\n2. 推起至手臂伸直\n3. 缓慢下放至胸部两侧", "tips": "相比杠铃，哑铃可提供更长的运动行程"},
    {"name": "自重深蹲", "name_en": "Bodyweight Squat", "muscle_group": "legs", "muscle_subgroup": "quadriceps", "category": "compound", "is_compound": True, "equipment": "bodyweight", "difficulty": "beginner", "calories_per_min": 7.0, "description": "新手友好的基础深蹲变式", "instructions": "1. 双脚与肩同宽\n2. 下蹲至大腿与地面平行\n3. 脚跟发力站起", "tips": "初学者可用手扶墙辅助平衡"},
    {"name": "锤式弯举", "name_en": "Hammer Curl", "muscle_group": "arms", "muscle_subgroup": "biceps", "category": "isolation", "is_compound": False, "equipment": "dumbbell", "difficulty": "beginner", "calories_per_min": 4.0, "description": "训练肱肌和肱桡肌，增加手臂正面的厚度", "instructions": "1. 站直或坐姿，双手持哑铃，掌心相对\n2. 屈肘弯举至肩部\n3. 缓慢下放", "tips": "手腕保持中立位，不要转动手掌"},
    {"name": "俄罗斯转体", "name_en": "Russian Twist", "muscle_group": "core", "muscle_subgroup": "obliques", "category": "isolation", "is_compound": False, "equipment": "bodyweight", "difficulty": "beginner", "calories_per_min": 5.0, "description": "锻炼腹斜肌和核心旋转力量", "instructions": "1. 坐姿，身体后倾，双脚抬离地面\n2. 双手在胸前合十\n3. 左右旋转躯干", "tips": "初学者可将脚放在地面上"},
    {"name": "绳索夹胸", "name_en": "Cable Crossover", "muscle_group": "chest", "muscle_subgroup": "middle_chest", "category": "isolation", "is_compound": False, "equipment": "cable", "difficulty": "beginner", "calories_per_min": 5.0, "description": "孤立训练胸大肌，精选胸沟塑形", "instructions": "1. 站在绳索器械中间，双手各握把手\n2. 手臂微弯向前夹胸至双手交汇\n3. 缓慢打开还原", "tips": "顶峰收缩时用力挤压胸肌"}
]


async def seed_exercises(db: AsyncSession):
    existing = await db.execute(select(Exercise.name))
    existing_names = {row[0] for row in existing.all()}

    count = 0
    for ex_data in SEED_EXERCISES:
        if ex_data["name"] not in existing_names:
            db.add(Exercise(**ex_data))
            count += 1

    if count > 0:
        await db.flush()
